### ISSUE TITLE
Missing sets.json

### ISSUE THREAD

**Issue by UgoRomi** [arnaudh/magic-card-zoom#4]
When trying to run `node src/js/util/download_all.js` after installing all the prerequisites and dependencies it gives an error because it can't find the file _sets.json_ under _assets/metadata/sets_

**Comment by arnaudh** [comment]
Hi @UgoRomi, sorry for the delay in response, as I only just saw your message. I hadn't realised I wasn't watching my own repo...
In any case, thanks for trying out MagicCardZoom and reporting this issue!

This is indeed a bug, which I hadn't picked up because I hadn't tried installing from scratch in a while.
I pushed a fix to `master` so if you pull you should not see this issue anymore (commit containing the fix: https://github.com/arnaudh/magic-card-zoom/commit/b23a013979226d7168a5a69d792d2d636108f0b5).

Let me know if you have any other issues, and thanks again for the report!
